# [ICTCOG AI Academy] 7기 고급시각저녁반
# Tensorflow를 활용한 기계학습/딥러닝 (2)

### tensor, Numpy 차이 

### 학습목표
1. tf.Tensor (immutable), tf.Variable(제약조건 하에 mutable처럼 바꿈) 차이
  - 상호호환 가능
2. 저수준 프로그래밍  

### 1. tf.Tensor, tf.Variable

### Tensor 특징
 1. GPU 사용
  - Numpy도 GPU 사용 가능해질 것
 2. Immutable
  - mutable 의 copy, inplace 제외
 3. 메소드명


In [1]:
import tensorflow as tf

tf.debugging.set_log_device_placement(True)
- 기본 False
- True 인 경우 어느 장치에서 실행 되는지 명시

In [2]:
tf.debugging.set_log_device_placement(True)  

##### 상수constant


In [3]:
a=tf.constant([1,2,3])

In [4]:
a+a  

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [6]:
for i in a:
  print(i)

Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(1, shape=(), dtype=int32)
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(2, shape=(), dtype=int32)
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(3, shape=(), dtype=int32)


#### 변수 Variable

-> shared, persistment state
  - 값을 변경 가능하고 지속됨
  - 상태따라 저장 가능
  - Python data persistent 파일 저장
- > tracked 메소드 통한 관리
- shape, dtype 에 따라 값 할당 여부 결정


모든 연산에서는 GPU 사용하지 않음

In [8]:
tf.Variable([1,2,3])  #클래스/객체   int32

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [29]:
a= tf.Variable( 1. )  #float32 

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0


In [30]:
id(a)

140110513570872

In [31]:
a.shape # shape 동일해야함

TensorShape([])

#### assign
- shape, dtype 일치해야 변경 가능

값을 할당 하므로써 자신을 바꿀 수 있음

In [32]:
a.assign(3) #shape 에 맞춰 값을 바꿈

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=3.0>

In [33]:
id(a)  #주소 동일함 

140110513570872

In [34]:
a

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [35]:
a= tf.Variable( 2 )
a.shape 

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


TensorShape([])

In [36]:
a.dtype

tf.int32

In [37]:
id(a)

140110486376232

In [40]:
a.assign( 3 ) #Variable 

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=3>

#### 호환
- 호환 : 메소드 보다는 함수(변환)
  - convert_to_tensor 텐서로 변환
  - .numpy()          넘파이로 변환

- 상수 미분하면 0이므로 변수 사용

In [43]:
t= tf.convert_to_tensor(a) #Variable  -> 텐서로 변환
t

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [44]:
tf.Variable(t) #텐서 -> Variable

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [45]:
a.numpy()  #tf -> numpy

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


3

- reshape 불가
  - 내부적으로 **copy**해서 새로운 텐서 생성

In [47]:
b= tf.reshape(a,[1])

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:GPU:0


In [48]:
id(a), id(b) #reshape 하게 되면 id값이 변경됨

(140110486376232, 140110485766920)

- 파이써 기반 TF Python 객체와 동일한 생명 주기를 갖음
> - `trainable  = True/ False`: 학습 여부 선택


### 1. 저수준 프로그래밍  
- Numpy -> Tensor 상호호환 가능 
  - Numpy: 다양한 기능 제공
  - Tensor: GPU,TPU
- 이미 만들어진 기능을 사용하는게 더 편리함



In [1]:
import numpy as np
import tensorflow as tf

2차식 찾기
- $ y=  ax^2 +bx+c $ 
   - 최적의 변수 $a,b,c$ 찾기


In [2]:
#학습을 통해서에 가장 적합한 변수 w 찾기
w=tf.Variable(tf.random.normal([3,1])) #a,b,c 값 랜덤 생성
w

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.5311235 ],
       [-0.76440626],
       [-0.03523445]], dtype=float32)>

In [4]:
optimizer= tf.optimizers.Adam( .1) #NN에서 많이 사용하는 adam 옵티마이저 사용

In [13]:
def model(x):
  f=tf.stack( [tf.square(x),x,tf.ones_like(x)],1)
  yhat=tf.squeeze(tf.matmul(f, w),1)      #차원
  return yhat

In [14]:
def loss_computed(yhat,y):  #loss 최소화 
  loss =tf.nn.l2_loss( yhat-y)  + 0.1 * tf.nn.l2_loss(w)  
  return loss

데이터는 가장 범용적인 Numpy로 주로 사용
- resource 주의

In [15]:
def generator_data(): 
  ''' 가짜데이터 생성'''
  x= np.random.uniform(-10,10,size=100).astype('f4')
  y= 5*np.square(x) +2
  return x,y

In [16]:
#학습
def train_step():
  x,y=generator_data()         # 가짜 데이터 생성
  def _loss():
    yhat= model(x)             # 모델 
    loss=loss_computed(y,yhat) # loss 최소화
    return loss
  optimizer.minimize(_loss, [w] ) # 함수형 패러다임 ->인자를 함수로

In [17]:
for _ in range(100): # 학습
  train_step()

In [18]:
w.numpy()            # 학습 후 변경됨

array([[5.0059676 ],
       [0.01955208],
       [4.388008  ]], dtype=float32)

> #### TF 5가지 구현 방식
  1. Tensor 저수준 구현
  2. Estimator
  3. keras 의 Sequential  
  - [텐서플로우 공식 문서 예시](https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ko)
    - 복잡한 모델 만들기 불가한 단방향 모델
  4. keras 의 Model  **함수형 패러다임 방식**
  5. keras 의 Model 상속



 > [Effective TF2.0](https://www.tensorflow.org/guide/effective_tf2?hl=ko)
  - keras 전면 도입
  - 함수형 패러다임 
  - 케라스 layer 과 모델을 사용

  - 이론과 실제의 간극을 줄임
    - 누구나 쉽게 사용 가능 
    - 다양성 부족, 복잡한 모델 생성 불가
    - 함수형 패러다임 사용


#### Functional Paradigm
1. 함수 선언/정의
  - control flow 사용
2. composition / recursion 

- 장점: 형식적 증명 가능성 
  - 이론,실제의 간극을 줄임

- Python의 함수는 First-class Function/ higher-order function
  - 함수를 객체처럼 사용
  - callable : `()` 붙이는 여부
    - 클래스, 함수, `__call__` 정의된 클래스의 인스턴스


두가지 형태
  1. function
  2. class/object를 function 처럼 

In [19]:
a= int()

In [20]:
a() #not callable

TypeError: ignored

### 3.  keras 의 Sequential  
- 모델을 함수로 만듦
- 함수형 패러다임 + 객체지향 패러다임 혼용
- tf.keras.models.Sequential
  - **가장 간단한 단반향 모델**
    - 간단한 신겸망 모델은 단반향으로 충분 
      - Feed forward, backpropagation
      - 각 레이어의 출력은 그 다음 레이어의 입력이 되어 reduction함
  -  `tf.keras.models.Model`로 부터 상속 받음

- 신경망의 각 레이어를 함수로 볼수 있음
- 모델은 각 레이어로 이루어진 합성함수

In [21]:
import tensorflow as tf

In [25]:
model= tf.keras.models.Sequential() #Sequential 모델은 함수

In [26]:
callable(model)  #callable 임

True

In [27]:
model_= tf.keras.models.Model()

In [28]:
issubclass(model.__class__ , model_.__class__) #Model로부터 상속해서 간단하게 만듦

True

### Dense
- fully connected/ dense
- neuron/unit 갯수


In [29]:
layer = tf.keras.layers.Dense(16 )  #이미 구현된 dense 레이어( 16개의 뉴론) 

In [30]:
callable(layer) #() 붙일수 있음

True

레이어 조합해서 모델 구축
1. 모델 함수 선언, 정의
2. model.add : 동적으로 레이어 추가 가능 
  - 전이 학습에 유용

In [32]:
model =tf.keras.models.Sequential([
   tf.keras.layers.Dense(16 ) ,
   tf.keras.layers.Dense(16 )                                 
])

In [33]:
model.layers

In [34]:
model.add(tf.keras.layers.Dense(16 )) #동적으로 추가 삭제

In [35]:
model.layers

이론, 실제와의 간극을 줄임

- 행렬곱 : dense 인경우 matrix dot 연산으로도 볼 수 있음
  - shape 중요함
  - 처음과 끝만 알면 중간의 shape 자동 계산 가능 




### layer 
- layer input, output 맞춰야함
- input layer는 값 그대로를 입력 받기 때문에 레이어로 고려하지 않음
  - keras에서는 input 레이어 쓰기도 하고 안쓰기도 함
- 3-layers
  - output layer 포함한 경우
- 2-hidden layers
  - output layer 포함하지 않은 경우

#### input_shape



In [37]:
#input 을 지정하게 되면 output도 지정해야함
model =tf.keras.models.Sequential([
   tf.keras.layers.Dense(16 ,input_shape=(4,)) ,
   tf.keras.layers.Dense(16 )  ,
   tf.keras.layers.Dense(3 )                                    
])

### summary
- 모델 설명
- 각 레이어 별로 output shape, 파라미터 수 출력
  - 파라미터: weight, bias 갯수

> `None`  정해지지 않음
  

In [38]:
model.summary() #4 입력 -> 16개 -> 16개 -> 3개 출력

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_7 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 51        
Total params: 403
Trainable params: 403
Non-trainable params: 0
_________________________________________________________________


In [39]:
import numpy as np
a= np.arange(20).reshape(5,4)  #

In [43]:
model(a)  #모델은 함수

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 0.32624972,  0.6002434 , -0.25527495],
       [ 1.2526925 ,  0.9425938 ,  1.3828313 ],
       [ 2.179135  ,  1.2849454 ,  3.0209367 ],
       [ 3.105577  ,  1.6272985 ,  4.6590424 ],
       [ 4.0320206 ,  1.9696491 ,  6.297149  ]], dtype=float32)>

In [42]:
model.layers[0](a) #각 레이어는 함수 

<tf.Tensor: shape=(5, 16), dtype=float32, numpy=
array([[ -0.4263265 ,  -0.98507565,   1.8777449 ,  -0.82631946,
         -1.3081961 ,   1.0814507 ,   1.341785  ,   0.8079012 ,
          0.27752775,   0.35215113,   0.20101613,  -0.7732402 ,
         -0.35533544,  -0.90486187,   0.5761624 ,  -0.33124882],
       [ -1.669876  ,  -3.6446903 ,   6.1437006 ,  -1.005423  ,
         -2.4005523 ,   5.4749765 ,   4.033854  ,   3.2240946 ,
         -1.9406427 ,   0.22596169,   0.49552202,  -3.0633862 ,
          0.19820291,  -3.0358622 ,   2.3066592 ,  -3.426939  ],
       [ -2.9134254 ,  -6.304305  ,  10.4096575 ,  -1.1845264 ,
         -3.492909  ,   9.868502  ,   6.725924  ,   5.6402884 ,
         -4.1588135 ,   0.09977198,   0.7900281 ,  -5.3535323 ,
          0.7517412 ,  -5.1668625 ,   4.037156  ,  -6.5226293 ],
       [ -4.1569743 ,  -8.963919  ,  14.675612  ,  -1.36363   ,
         -4.585265  ,  14.262027  ,   9.417994  ,   8.056481  ,
         -6.3769836 ,  -0.02641726,   1.0845339 ,  -

#### tf.keras.layers.Input
input이 레이어인 경우

In [45]:
model =tf.keras.models.Sequential([ #위와 동일한 모델
   tf.keras.layers.Input(shape=(4,)),
   tf.keras.layers.Dense(16 ) ,
   tf.keras.layers.Dense(16 ) ,
   tf.keras.layers.Dense(3 )                  
])

In [47]:
model.summary()  

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_10 (Dense)             (None, 16)                272       
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 51        
Total params: 403
Trainable params: 403
Non-trainable params: 0
_________________________________________________________________


tensor와 numpy 상호호환 가능

In [46]:
model(a)   # 모델은 함수

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[  0.09218484,   0.9104215 ,  -1.8289139 ],
       [ -1.1155668 ,   2.9936497 ,  -5.5287285 ],
       [ -2.3233187 ,   5.0768785 ,  -9.228545  ],
       [ -3.531072  ,   7.1601057 , -12.928359  ],
       [ -4.738825  ,   9.243334  , -16.628176  ]], dtype=float32)>

OpenCV연습용 데이터 텐서에 넣음
- 

In [48]:
from sklearn.datasets import load_iris

In [50]:
data = load_iris()

In [52]:
import pandas as pd

In [54]:
import seaborn as sns

모델 구축에서 input,output shape 가장 중요

In [56]:
iris= sns.load_dataset('iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### 기계학습 기본 
- **전통정 기계학습은 1차원 데이터**
  - 하나의 sample(행) 1차원, sample들을 모아서 2차원 
학습용 데이터 세트- 데이터의 속성들을 각 sample 로 
 - 차원 갯수가 중요하며 sample 갯수는 중요하지 않음


 - iris 속성 4개를 넣어서 3개중 어떤 종류인지 맞추는 모델



In [58]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(16, input_shape=(4,))
])

In [60]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 16)                80        
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [59]:
model(data.data)  # shape 변화 : (150,4)x (4,16) = (150,16)

<tf.Tensor: shape=(150, 16), dtype=float32, numpy=
array([[-2.635682  ,  0.04924071,  0.2614827 , ..., -2.4311523 ,
         3.09484   ,  1.8674374 ],
       [-2.4450362 ,  0.16956311,  0.06255744, ..., -2.192677  ,
         2.8181448 ,  1.720649  ],
       [-2.4184227 ,  0.04599544,  0.23180565, ..., -2.2266154 ,
         2.844287  ,  1.7255437 ],
       ...,
       [-2.3266048 , -1.0362624 , -0.6680014 , ..., -3.4649663 ,
         4.479195  ,  4.292474  ],
       [-2.204974  , -1.4818072 , -0.3493249 , ..., -3.6136627 ,
         4.7021713 ,  4.6226377 ],
       [-2.1504374 , -1.1452135 , -0.5837538 , ..., -3.488522  ,
         4.319103  ,  4.1330066 ]], dtype=float32)>

In [66]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(6, input_shape=(4,)),
                                    tf.keras.layers.Dense(5)
])

In [69]:
model(data.data)  #  (150,4) x (4,6 ) x (6x5) = (150x5) 

<tf.Tensor: shape=(150, 5), dtype=float32, numpy=
array([[-7.36866045e+00,  1.03680718e+00, -3.41513824e+00,
         1.58825171e+00,  1.94518840e+00],
       [-6.95898676e+00,  9.76166964e-01, -3.38812971e+00,
         1.64383662e+00,  1.82993746e+00],
       [-6.78014135e+00,  9.55190003e-01, -3.14812636e+00,
         1.46417212e+00,  1.78811932e+00],
       [-6.68845415e+00,  9.45380151e-01, -3.17895150e+00,
         1.32171202e+00,  1.75482559e+00],
       [-7.29361868e+00,  1.02903080e+00, -3.31545210e+00,
         1.47135890e+00,  1.92622030e+00],
       [-7.88927603e+00,  1.13183880e+00, -3.54364944e+00,
         1.42673290e+00,  2.06466007e+00],
       [-6.74575329e+00,  9.64450240e-01, -3.00441003e+00,
         1.22158742e+00,  1.77088261e+00],
       [-7.24821234e+00,  1.02157307e+00, -3.40533161e+00,
         1.49991381e+00,  1.90801215e+00],
       [-6.36127186e+00,  8.98638964e-01, -3.03744102e+00,
         1.30740297e+00,  1.66882801e+00],
       [-7.05002642e+00,  9.8286

In [68]:
model.summary() # (4)

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_16 (Dense)             (None, 5)                 35        
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________


In [71]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(3, input_shape=(4,)),
                                    tf.keras.layers.Dense(7),
])

In [72]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_20 (Dense)             (None, 7)                 28        
Total params: 43
Trainable params: 43
Non-trainable params: 0
_________________________________________________________________


In [73]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(4, input_shape=(4,)),
                                    tf.keras.layers.Dense(3),
                                    tf.keras.layers.Dense(3) #결과 3개 
])

In [74]:
model.summary()  # (150 x 4 ) x (4x3)x(3x3)= (150x3)

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_22 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 12        
Total params: 47
Trainable params: 47
Non-trainable params: 0
_________________________________________________________________


> Logistic regression 
  - 2진 분류이나 one ve one, one vs rest , one vs all 방식
  - sigmoid 함수를 이용해서 threshold 기준으로 이진 분류 

- ANN/ MLP 최종 노드의 결과값은 행렬곱의 결과로 나옴


- regression : 실수값 y 예측 
- binary class: 2개의 클래스 분류 
- multi-class : 3개 이상의 클래스 분류
- multi label : 2개 이상의 라벨 분류 , 2개 이상 선택


### multi-class 
- setosa, virginica, versicolor 3종류의 iris 
- one-hot encoding vs label encoding
> - 모델 구성에 따라 supervised learning 의 classification, regression 과 unsupervised  learning 모델도 만들 수 있음

####  one-hot encoding
- dummy variable 형식으로 각 종류로 표현
- one-hot encoidng 된 값과 가장 가깝게 만들도록 함
> 예.  setosa: 100, virginica: 010, versicolor: 001




In [76]:
data.data[0]  #0번째 데이터

array([5.1, 3.5, 1.4, 0.2])

In [78]:
model(data.data[[0]])  #2차원 맞춰야함

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.10602753, -1.0467125 ,  1.638782  ]], dtype=float32)>

In [79]:
model(data.data[0][tf.newaxis]) 

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.10602753, -1.0467125 ,  1.638782  ]], dtype=float32)>

In [80]:
model(data.data[1][tf.newaxis]) 

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.0760129, -1.0913991,  1.4612209]], dtype=float32)>

#### label encoding 방식
- 결과 하나 나오면 >label encoding 으로 가능
- 고유속성과 Label 값이 반영하지 못해서 성능이 좋지 않아 잘 사용하지 않음
> 예.  setosa: 1, virginica: 2, versicolor: 3


> y값이 실수인 경우 regression



input_shape  구성과 output 레이어의 뉴론 갯수 중요


- 어떻게 처리 해야하는지 다룰 예정
- 이미지 데이터 

In [81]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(4, input_shape=(4,)), 
                                    tf.keras.layers.Dense(3),
                                    tf.keras.layers.Dense(1) #결과 1개 
])
model(data.data[0][tf.newaxis])   

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.3496525]], dtype=float32)>