# [ICTCOG AI Academy] 7기 고급시각저녁반
# Tensorflow를 활용한 기계학습/딥러닝 (1)

## 학습목표
1. Pytorch 를 통한 Tensorflow 이해
2. Tensorflow 구현 방법 이해
  
### 1. Pytorch 를 통한 Tensorflow 이해
- [튜토리얼 : 초보자, 고급](https://www.tensorflow.org/lite/tutorials?hl=ko)
- [가이드](https://www.tensorflow.org/lite/guide?hl=ko)
- [ LEARNING PYTORCH WITH EXAMPLES ](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html) 

- backpropagation 신경망 학습 
  - computer로 구현하는 4가지 기법(논문) 중 2가지
    - Numpy : array, matrix 지원
      - 저수준
      - 현대적이지 않음 ( GPU 지원하지 않음)
    - 자동미분  Autograd, Auto differentiation 지원
      - 상위개념
 
#### Pytorch, Tensorflow
- 객체지향 
  - 상속, 오버라이딩 활용
  - 모델을 객체로 만들어서 재사용

- 함수형 패러다임
  - custom 가능
  - 모델 복잡 할 수록 control flow 조절

### 2. Tensorflow 구현 방법 이해
##### Tensorflow2 5가지 
- 각 방법은 서로 목적이 상이함

1. tf.nn 
  - 가장 저수준
    - 가장 기본적이고 나머지 직접 구현해야함
  - 텐서에서 지원하지 않는 새로운 기법들
  - 특히 연구용 -> PyTorch

2. Estimator  기존에 정의된 것을 이용한 prototype
  - TF에서 NN은 Keras 사용 권장
  - ensemble 의 **boosting** 기법 : xgboost, LightGBM
    - TF에서는 기본적으로 기계학습에 필요한 필수적 기능이 없어서 Scikit-learn과 연동시켜서 활용
    - Scikit-learn GPU 사용 불가
      - > Q: Will you add GPU support?
          - A: No, or at least not in the near future. The main reason is that GPU support will introduce many **software dependencies** and introduce platform specific issues .... 
    - TensorFlow에서 GPU 사용하도록 지원

3. ### keras
  - 상속: 커스터마이징 
  - **함수형 패러다임 방식**
    -  multi-inputs, multi-outputs 사용
  - 기본적 객체지향
    - 이미 만들어진 모델 가져와서 composition 방식으로 재조합


In [ ]:
import this  #명백한 방법은 1가지 

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
import tensorflow as tf

In [ ]:
dir(tf.nn)  #신경망 기반 

['RNNCellDeviceWrapper',
 'RNNCellDropoutWrapper',
 'RNNCellResidualWrapper',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'all_candidate_sampler',
 'atrous_conv2d',
 'atrous_conv2d_transpose',
 'avg_pool',
 'avg_pool1d',
 'avg_pool2d',
 'avg_pool3d',
 'batch_norm_with_global_normalization',
 'batch_normalization',
 'bias_add',
 'collapse_repeated',
 'compute_accidental_hits',
 'compute_average_loss',
 'conv1d',
 'conv1d_transpose',
 'conv2d',
 'conv2d_transpose',
 'conv3d',
 'conv3d_transpose',
 'conv_transpose',
 'convolution',
 'crelu',
 'ctc_beam_search_decoder',
 'ctc_greedy_decoder',
 'ctc_loss',
 'ctc_unique_labels',
 'depth_to_space',
 'depthwise_conv2d',
 'depthwise_conv2d_backprop_filter',
 'depthwise_conv2d_backprop_input',
 'dilation2d',
 'dropout',
 'elu',
 'embedding_lookup',
 'embedding_lookup_sparse',
 'erosion2d',
 'fixed_unigram_candidate_sampler',
 'fractional_avg_pool',
 'fra

#### Numpy 와 Tensor 차이
1. **immutable** 데이터 타입
    - 자기 자신이 바뀌지 않음
    - 상수(재할당 불가), 변수 ( 재할당 할 수 있음)
    - 함수형 패러다임
2. **GPU 지원 여부**
  > 텐서플로우 tf.experimental.numpy : **Numpy API 넘파이도 최적화**하여 효율적으로 사용할 수있도록 지원(정식버전 아님)
3. method 명, numerical stability 로 인한 차이
  - method 명이 같은 경우라도 사용 방식이 다름
  - Tensorflow가 **elegant**(명확)

###### 프로그래밍 패러다임
- 명령형
  - 절처적
  - 객체지향
- 선언형
  - 함수형
> TF : 유기적으로 객체지향,함수형, array programming 을 상황에 맞게 유기적으로 연동


###### Numpy, Tensor호환 
1. Numpy -> Tensorflow  method
  - tensor로 변환
    - 연습용 데이터가 numpy로 구성된 이유
    - 변환 resource 필요
      - 호스트 메모리 복사가 필요함
      - 영상처리에서는 민감한 사항(처리)
2.  Tensorflow -> Numpy method
  - Numpy로 변환
  - 상대적으로 resource 덜 필요
  - > 메모리를 **공유**하기 때문에 이러한 변환은 일반적으로 간단




In [ ]:
dir(tf) #numpy/Tensor 데이터 타입인지 체크해서 변환해서 실행

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_API_MODULE',
 '_LazyLoader',
 '__all__',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__internal__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__operators__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_absolute_import',
 '_api',
 '_compat',
 '_current_file_location',
 '_current_module',
 '_distutils',
 '_division',
 '_estimator_module',
 '_fi',
 '_inspect',
 '_ll',
 '_logging',
 '_main_dir',
 '_major_api_version',
 

In [ ]:
import numpy as np

In [ ]:
x= tf.constant([1,2,3])

In [ ]:
x.numpy()  # tensor -> numpy array

array([1, 2, 3], dtype=int32)

In [ ]:
np.add(x,x) # tensor -> numpy array

array([2, 4, 6], dtype=int32)

In [ ]:
import seaborn as sns
iris= sns.load_dataset('iris')
type(iris)   # DataFrame

pandas.core.frame.DataFrame

In [ ]:
iris.values  # numpy array

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [ ]:
iris.to_numpy() #DataFrame - > numpy array 로 변환

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

#### Numpy vs Tensorflow
- method 명 차이
  - tensor가 elegant
  - `.numpy()` 모든 tensor는 numpy로 바꿀 수 있음
  - numpy가 연산을 효율적으로 함
  - broadcasting

  

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
x = np.random.normal(size=[10,10])  #size
x

array([[-0.58656441, -1.44971611,  0.17396113, -0.3219968 , -1.24995412,
        -2.04296749, -0.21081203,  0.15012722, -0.05707896, -1.54306507],
       [ 1.16793246, -2.22064506,  1.47054248,  1.97522578, -0.14700766,
        -1.79946269, -0.2209306 , -0.33353088,  0.54952405,  0.07181854],
       [ 0.88516167,  1.97397307, -0.86078962, -0.85112211, -0.55603749,
         0.82479245, -0.2848654 , -0.61565763, -0.03807773, -0.68547521],
       [ 0.03271972, -1.00819712, -1.41400247, -0.70584963, -1.12129613,
        -0.94671053, -0.27165996, -0.18252284,  1.65240444, -0.68681266],
       [-0.47187196, -0.79591338, -0.01295625,  0.40418035,  0.07053242,
         0.24367051, -0.66643909, -1.05521969, -0.65524724, -0.16750839],
       [-0.83141564,  0.88567092,  2.54072104, -1.86791693, -0.79352988,
         0.54089653,  0.54750206, -1.10308137,  0.29666695, -0.15613442],
       [ 0.1770898 ,  0.74040794,  0.15836509,  0.49401704, -3.08208757,
         0.5193929 , -0.24960203, -2.21834951

In [ ]:
y = np.random.normal(size=[10,10])  #10x10 matrix
y

array([[ 2.21159505, -0.82045357,  1.06493654,  0.26689604,  1.76949729,
        -0.51726031,  0.19742402, -2.04101978,  0.43934248,  0.0398356 ],
       [ 0.47888088, -0.56054611, -0.49584922, -0.37723654,  0.58923914,
         0.86401991, -2.00559931,  0.44750716, -1.19033049, -1.63506248],
       [ 0.47032089,  0.45385186, -0.89348449, -0.13313212, -1.03920576,
         0.54637909,  0.41609226, -0.06735599,  0.71320067,  0.3152394 ],
       [ 0.70048696, -0.29757607,  1.21838232,  0.06802417,  0.66042324,
        -1.49160126, -0.25712714,  1.28543995, -0.24985386, -0.84163575],
       [-1.72347207, -0.56028456,  0.65624616,  1.12712705,  0.31416126,
        -1.04748206, -0.67097652,  0.26376474,  1.70459957, -0.25964155],
       [ 0.80032055, -1.50636926,  0.07092325, -0.72655486, -0.45366208,
         0.97943282,  0.94996982,  2.31980406, -0.72223422,  0.715532  ],
       [-1.39136923,  1.37845261, -0.48165484, -0.4654942 ,  1.41682109,
        -0.18512752,  0.12206723,  0.20023412

In [ ]:
z= np.dot(x,y) #array
z

array([[ 0.14457382,  4.75568845, -3.08528266, -1.41409562, -1.2710976 ,
        -4.35284578,  2.33262525, -5.50142378,  0.4082138 , -0.05448147],
       [ 2.66758381,  2.9846686 ,  3.35757578,  2.80486464,  0.91232301,
        -5.81066929,  4.54847543, -5.4952739 ,  5.03925215,  1.59342048],
       [ 5.15527436, -4.41518446, -0.05842916, -1.72438211,  3.02917098,
         2.30314603, -2.07129508, -1.01204443, -3.37241995, -3.10340158],
       [ 0.05813073,  3.19081646, -1.96568864, -0.35828636, -0.25040379,
        -1.29363246,  5.44837259, -4.50825053, -1.97670076,  1.96967182],
       [ 1.23006878, -2.96075927,  3.17775172,  1.20815452, -0.70944325,
        -0.81579415,  0.99707434,  0.76068712,  3.10684513, -0.16284515],
       [ 0.4685928 ,  0.92616544, -5.19035377, -1.61230694, -3.70886925,
         6.84457997,  2.27606559, -0.29164159, -1.98092359,  0.8596028 ],
       [ 8.96553155, -1.54735996, -0.35484095, -2.31009461,  0.55503794,
         3.67321406,  6.80722881, -1.29276537

In [ ]:
print(z) # list로 보임

[[ 0.14457382  4.75568845 -3.08528266 -1.41409562 -1.2710976  -4.35284578
   2.33262525 -5.50142378  0.4082138  -0.05448147]
 [ 2.66758381  2.9846686   3.35757578  2.80486464  0.91232301 -5.81066929
   4.54847543 -5.4952739   5.03925215  1.59342048]
 [ 5.15527436 -4.41518446 -0.05842916 -1.72438211  3.02917098  2.30314603
  -2.07129508 -1.01204443 -3.37241995 -3.10340158]
 [ 0.05813073  3.19081646 -1.96568864 -0.35828636 -0.25040379 -1.29363246
   5.44837259 -4.50825053 -1.97670076  1.96967182]
 [ 1.23006878 -2.96075927  3.17775172  1.20815452 -0.70944325 -0.81579415
   0.99707434  0.76068712  3.10684513 -0.16284515]
 [ 0.4685928   0.92616544 -5.19035377 -1.61230694 -3.70886925  6.84457997
   2.27606559 -0.29164159 -1.98092359  0.8596028 ]
 [ 8.96553155 -1.54735996 -0.35484095 -2.31009461  0.55503794  3.67321406
   6.80722881 -1.29276537 -6.66693285 -0.90068742]
 [-4.93678608  0.67203059 -0.86241769  1.47474483 -0.5530612   2.31623263
  -1.78930956 -2.03107246  1.8436357   1.15903227]


numpy대신 tensor 사용하지 않는 이유
- NN 기반 아닐 경우, GPU 가 성능향상 미비
- GPU 는 platform dependent 해서 범용적이지 못함
- Numpy 다양한 메소드 지원

In [ ]:
xx = tf.random.normal([10,10] )  # shape  10x10 ; 기본 dtype float32, 
xx

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-1.8004117 ,  0.12082984,  1.0753385 , -0.04630368,  0.20902982,
        -1.1294465 ,  0.44027522, -0.20458777,  0.17131874,  0.23528777],
       [-1.1255958 , -0.9423221 , -0.22508086,  2.4745536 ,  0.84882   ,
        -0.5859348 ,  1.2550557 ,  2.2290576 ,  0.60170716, -0.68877596],
       [-0.4083108 , -0.30175054,  0.30496922,  0.13767713, -0.98358727,
        -1.1745007 , -0.91338986,  1.0383446 ,  0.5057797 ,  0.64041406],
       [-1.2675546 , -0.67615175, -1.2692634 ,  0.7844826 , -0.3545462 ,
        -2.5669277 ,  0.15864544, -0.61057246, -1.5688559 , -1.3448335 ],
       [-1.0376859 ,  0.06693215,  1.2674869 ,  1.4594126 , -0.2505913 ,
        -0.7636152 ,  0.01987569,  0.01010553, -0.17264955, -0.7287092 ],
       [ 0.66256285, -0.95512897,  1.4681269 , -0.20209633,  0.7619833 ,
        -0.2802632 , -0.90252715,  0.22961937,  0.09292863, -0.09639087],
       [ 0.8050617 , -1.50617   , -0.41049966,  0.595928  ,  0.15285

In [ ]:
print(xx) #tf.Tensor 라고 명시되어 있음

tf.Tensor(
[[-1.8004117   0.12082984  1.0753385  -0.04630368  0.20902982 -1.1294465
   0.44027522 -0.20458777  0.17131874  0.23528777]
 [-1.1255958  -0.9423221  -0.22508086  2.4745536   0.84882    -0.5859348
   1.2550557   2.2290576   0.60170716 -0.68877596]
 [-0.4083108  -0.30175054  0.30496922  0.13767713 -0.98358727 -1.1745007
  -0.91338986  1.0383446   0.5057797   0.64041406]
 [-1.2675546  -0.67615175 -1.2692634   0.7844826  -0.3545462  -2.5669277
   0.15864544 -0.61057246 -1.5688559  -1.3448335 ]
 [-1.0376859   0.06693215  1.2674869   1.4594126  -0.2505913  -0.7636152
   0.01987569  0.01010553 -0.17264955 -0.7287092 ]
 [ 0.66256285 -0.95512897  1.4681269  -0.20209633  0.7619833  -0.2802632
  -0.90252715  0.22961937  0.09292863 -0.09639087]
 [ 0.8050617  -1.50617    -0.41049966  0.595928    0.15285139 -0.03240962
   1.8131981  -2.6737134   0.75289136  0.26107755]
 [-0.21101563  0.6177408   0.99624753  0.01732492 -0.79003054 -0.9358426
  -1.4736557  -0.4220345  -1.055438    0.761101

#### Numpy
- mutable: 재할당 없이 자신의 값 변화 가능

#### TensorFlow
- **immutable** 
- 상수 constant : python에서는 존재하지 않음,재할당 할 수 없음
- 변수 Varaiable : 재할당 할 수 있음
  - mutable 은 아니지만 비슷함
  - 활용 : 학습


In [ ]:
a= tf.constant([1,2,3])  #상수
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
a.assign # 재할당 불가 

In [ ]:
b=tf.Variable([1,2,3]) #변수
b

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

#### 재할당

- 내부적으로 자기 자신 재할당
- id 동일

In [ ]:
# 내부적으로 b= b+x 처리 자기자신 재할당
b.assign_add([3,4,5]) 

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 6, 8], dtype=int32)>

In [ ]:
id(b)

139892033732056

In [ ]:
id(b) #id값이 동일함 

139892033732056

In [ ]:
b.assign_sub([3,4,5])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

### broadcasting
- Numpy와 동일하게 broadcasting 지원
- 모양이 상이해도 자동으로 맞추어서 계산

In [ ]:
np.array([[1,2,3],[4,5,6]])+ 1.0 #broadcasting

array([[2., 3., 4.],
       [5., 6., 7.]])

In [ ]:
np.array([[1,2,3],[4,5,6]]) + np.ones((2,3))

array([[2., 3., 4.],
       [5., 6., 7.]])

In [ ]:
bb= np.array([[1,2],[3,4]])
bb

array([[1, 2],
       [3, 4]])

In [ ]:
cc= np.array([[1],[2]])

In [ ]:
cc.shape

(2, 1)

In [ ]:
bb+cc   # broadcasting

array([[2, 3],
       [5, 6]])

In [ ]:
a = tf.constant([[1,2],[3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
b =  tf.constant([[1],[2]])
b

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [ ]:
a+b  # broadcasting

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [ ]:
np.broadcast
tf.broadcast_dynamic_shape # 나중에 다룰 예정 
tf.broadcast_static_shape

In [ ]:
np.repeat(b,2)  #원소 반복

array([1, 1, 2, 2], dtype=int32)

In [ ]:
np.tile(b,2)  # 원소 반복

array([[1, 1],
       [2, 2]], dtype=int32)

In [ ]:
a + tf.tile(b,[1,2]) #이름은 동일하지만 사용방식 상이함

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

ufunc

In [ ]:
sum([1,2,3])  #mutable만 가능

6

In [ ]:
np.sum(4)  #ufunc

4

In [ ]:
tf.add(1,2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.add([1,2],[3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [ ]:
np.add.reduce([1,2,3,4,5])

15

In [ ]:
tf.reduce_sum([1,2,3,4,5])  #직관적, 우아함 , numerical stability ( 나중에 다시 다룰 예정)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tf.add([1,2,],[3,4]) + tf.square(3)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([13, 15], dtype=int32)>

#### 연산자 오버로딩
- 모든 연산자는 대응하는 메소드가 있어 데이터 타입에 따른 연산자 기능 바꿀 수 있음
- 모든 메소드는 대응하는 함수로 바꿀 수 있음

- python에서는 메소드 오버로딩은 없지만 연산자 오버로딩은 있음

In [ ]:
from operator import add

In [ ]:
tf.square(2) + tf.square(3)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [ ]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### numerical stability 
- operator overloading 과도 관련 있음
- 언급 안한 부분은 Numpy와 비슷함!!!
- 

In [ ]:
x= tf.constant([1,2,3,4])

In [ ]:
dir(x) #  __iter__ -> itarable  -> for 사용;  __getitem__  인덱싱, 슬라이싱 지원

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_add_consumer',


모든 연산자는 대응하는 메소드가 있다.

In [ ]:
x[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.slice(x,[0],[3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

### reduce 

In [ ]:
x=tf.random.uniform([500,100])

In [ ]:
z=tf.zeros([100])
z

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [ ]:
%%time
for i in range(500):
  z += x[i]  #UnboundLocalError   함수 2개 중첩하는 경우                          lo

CPU times: user 59.2 ms, sys: 0 ns, total: 59.2 ms
Wall time: 58.9 ms


In [ ]:
z

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([244.15952, 257.11884, 249.86745, 250.84879, 242.79626, 254.66704,
       255.15791, 240.4988 , 255.67686, 255.75911, 251.50172, 250.73367,
       250.52681, 244.18956, 251.71777, 254.64616, 256.96478, 240.43103,
       249.14424, 255.56577, 258.42242, 256.85535, 233.9249 , 244.55524,
       239.81029, 249.5583 , 255.82655, 246.23015, 249.17886, 253.17743,
       246.04164, 246.10744, 259.76297, 256.99982, 263.3804 , 248.72911,
       246.54456, 248.07649, 240.11418, 250.29999, 252.06647, 254.49033,
       249.94167, 248.80566, 255.00354, 243.14394, 247.2759 , 254.95132,
       262.01532, 253.06075, 250.54771, 249.61807, 247.61543, 251.57497,
       244.54082, 247.52473, 243.73497, 253.63907, 250.37299, 252.9175 ,
       260.21268, 254.43533, 256.5002 , 242.49641, 250.51106, 242.24074,
       245.10173, 242.31387, 242.26434, 249.25156, 241.71948, 241.09032,
       248.13347, 251.0922 , 248.80914, 256.11646, 242.72144, 262.78195,
   

In [ ]:
len(tf.unstack(z)) #100개의 list

100

In [ ]:
list(tf.unstack(z))

[<tf.Tensor: shape=(), dtype=float32, numpy=244.15952>,
 <tf.Tensor: shape=(), dtype=float32, numpy=257.11884>,
 <tf.Tensor: shape=(), dtype=float32, numpy=249.86745>,
 <tf.Tensor: shape=(), dtype=float32, numpy=250.84879>,
 <tf.Tensor: shape=(), dtype=float32, numpy=242.79626>,
 <tf.Tensor: shape=(), dtype=float32, numpy=254.66704>,
 <tf.Tensor: shape=(), dtype=float32, numpy=255.15791>,
 <tf.Tensor: shape=(), dtype=float32, numpy=240.4988>,
 <tf.Tensor: shape=(), dtype=float32, numpy=255.67686>,
 <tf.Tensor: shape=(), dtype=float32, numpy=255.75911>,
 <tf.Tensor: shape=(), dtype=float32, numpy=251.50172>,
 <tf.Tensor: shape=(), dtype=float32, numpy=250.73367>,
 <tf.Tensor: shape=(), dtype=float32, numpy=250.52681>,
 <tf.Tensor: shape=(), dtype=float32, numpy=244.18956>,
 <tf.Tensor: shape=(), dtype=float32, numpy=251.71777>,
 <tf.Tensor: shape=(), dtype=float32, numpy=254.64616>,
 <tf.Tensor: shape=(), dtype=float32, numpy=256.96478>,
 <tf.Tensor: shape=(), dtype=float32, numpy=240.4

In [ ]:
%%time
for j in tf.unstack(x):
  z +=j                #속도가 4배 바름

CPU times: user 9.84 ms, sys: 1.94 ms, total: 11.8 ms
Wall time: 14.5 ms


In [ ]:
%time tf.reduce_sum(z)  #빠름!!!!

CPU times: user 700 µs, sys: 0 ns, total: 700 µs
Wall time: 768 µs


<tf.Tensor: shape=(), dtype=float32, numpy=49869.562>

연산자 오버로딩


AttributeError: ignored

In [ ]:
zz=-z

In [ ]:
zz

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([-488.3191 , -514.2375 , -499.7347 , -501.69748, -485.59256,
       -509.33395, -510.31598, -480.99738, -511.35364, -511.51813,
       -503.0034 , -501.4669 , -501.0538 , -488.37946, -503.43542,
       -509.29245, -513.9297 , -480.86206, -498.28824, -511.1314 ,
       -516.8452 , -513.71075, -467.84988, -489.1104 , -479.62082,
       -499.11642, -511.65353, -492.46072, -498.3582 , -506.35477,
       -492.083  , -492.2148 , -519.52563, -513.99945, -526.7612 ,
       -497.45816, -493.0895 , -496.15314, -480.22806, -500.60004,
       -504.13306, -508.98044, -499.88333, -497.61145, -510.00787,
       -486.28793, -494.5515 , -509.9029 , -524.0304 , -506.12155,
       -501.0956 , -499.23608, -495.23068, -503.1496 , -489.08173,
       -495.0491 , -487.46994, -507.2779 , -500.7455 , -505.83505,
       -520.42554, -508.87128, -513.0002 , -484.99323, -501.02188,
       -484.48117, -490.20346, -484.62753, -484.52902, -498.50305,
       -483.43

In [ ]:
tf.negative(z)

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([-488.3191 , -514.2375 , -499.7347 , -501.69748, -485.59256,
       -509.33395, -510.31598, -480.99738, -511.35364, -511.51813,
       -503.0034 , -501.4669 , -501.0538 , -488.37946, -503.43542,
       -509.29245, -513.9297 , -480.86206, -498.28824, -511.1314 ,
       -516.8452 , -513.71075, -467.84988, -489.1104 , -479.62082,
       -499.11642, -511.65353, -492.46072, -498.3582 , -506.35477,
       -492.083  , -492.2148 , -519.52563, -513.99945, -526.7612 ,
       -497.45816, -493.0895 , -496.15314, -480.22806, -500.60004,
       -504.13306, -508.98044, -499.88333, -497.61145, -510.00787,
       -486.28793, -494.5515 , -509.9029 , -524.0304 , -506.12155,
       -501.0956 , -499.23608, -495.23068, -503.1496 , -489.08173,
       -495.0491 , -487.46994, -507.2779 , -500.7455 , -505.83505,
       -520.42554, -508.87128, -513.0002 , -484.99323, -501.02188,
       -484.48117, -490.20346, -484.62753, -484.52902, -498.50305,
       -483.43

모든 연산자에는 대응하는 function이 있다

In [ ]:
tf.add(z,z)
tf.subtract(z,z)
tf.multiply(z,z)
tf.divide(z,z)
tf.pow([1,2],2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

[tensor](https://www.tensorflow.org/guide/tensor?hl=ko)
Numpy
- homogeneous container
 - 동일한 데이터 타입




In [ ]:
np.array([1,2,'1']) # 자동으로  ]

array(['1', '2', '1'], dtype='<U21')

In [ ]:
tf.constant([1,1,'1']) #강제로 에러 발생 -> pythonic!

ValueError: ignored

> EAFP: 허락보다는 용서를 구하기 쉽다.

- #type casting 형변환 as ,from




In [ ]:
tf.dtypes.cast #type casting

<function tensorflow.python.ops.math_ops.cast>

In [ ]:
tf.dtypes.DType #지원하는 모든 데이터 타입 확인

tensorflow.python.framework.dtypes.DType

- 내부적으로 넘파이처럼 C로 만들어짐
- C++, Java Script용 동시 지원


In [ ]:
#matlab 3개 2x5 
np.moveaxis
np.swapaxes
np.transpose
tf.transpose  #있는 것과 없는 것이 있음

<function numpy.transpose>

모든 종류의 연산에 사용

shape,axis, size , rank
- shape ,dtype 이 가장 중요함
- indexing, slicing 도 동일

In [ ]:
x=tf.constant([[1,2],[3,4]])

In [ ]:
x[...]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

type 변환
- Numpy : as,from
- Tensor : tf.cast

### 기본 데이터 타입
- 텐서플로우: 32 
- Pandas: 64
- Numpy: 시스템 플랫폼 따라
  - 연동하는 경우 내부적으로 알아서 타입변환함


In [ ]:
x=np.array([1,2,3])

In [ ]:
x.shape

(3,)

In [ ]:
x.astype('f4')  #타입 변화

array([1., 2., 3.], dtype=float32)

In [ ]:
np.asfarray(x)

array([1., 2., 3.])

In [ ]:
np.cast  #다름

{numpy.bool_: <function numpy.core.numerictypes.<lambda>>,
 numpy.bytes_: <function numpy.core.numerictypes.<lambda>>,
 numpy.complex128: <function numpy.core.numerictypes.<lambda>>,
 numpy.complex256: <function numpy.core.numerictypes.<lambda>>,
 numpy.complex64: <function numpy.core.numerictypes.<lambda>>,
 numpy.datetime64: <function numpy.core.numerictypes.<lambda>>,
 numpy.float128: <function numpy.core.numerictypes.<lambda>>,
 numpy.float16: <function numpy.core.numerictypes.<lambda>>,
 numpy.float32: <function numpy.core.numerictypes.<lambda>>,
 numpy.float64: <function numpy.core.numerictypes.<lambda>>,
 numpy.int16: <function numpy.core.numerictypes.<lambda>>,
 numpy.int32: <function numpy.core.numerictypes.<lambda>>,
 numpy.int64: <function numpy.core.numerictypes.<lambda>>,
 numpy.int8: <function numpy.core.numerictypes.<lambda>>,
 numpy.longlong: <function numpy.core.numerictypes.<lambda>>,
 numpy.object_: <function numpy.core.numerictypes.<lambda>>,
 numpy.str_: <function 

In [ ]:
tf.cast(x, 'int8') # 명시적, 유형별 캐스팅, 함수형

<tf.Tensor: shape=(3,), dtype=int8, numpy=array([1, 2, 3], dtype=int8)>

In [ ]:
x = tf.constant([x for x in range(10)]) 

In [ ]:
x.ref

<bound method Tensor.ref of <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>>

In [ ]:
x= np.arange(10).reshape(2,5) #
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
tf.reshape(x,[2,5])  # 통일성

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

메모리에서 복사가 일어나지 않아서 속도가 빠름

In [ ]:
tf.broadcast_to(tf.constant([1,2,3]),[3,3]) #(1,3) -> (3,3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [ ]:
np.broadcast_to(np.array([1,2,3]),(3,3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

> 영상에서는 다루지 않는 텐서
  - 비정형 텐서 ragged tensor
  - 희소 텐서 sparse