# [ICTCOG AI Academy] 7기 고급시각저녁반
# Learning technique

### 데이터 처리 (Python) with 도메인 지식
### EDA(통계적 지식 요구)
### 모델 (인공지능 - 딥러닝기법
  - 선형대수 /미적분

In [1]:
import tensorflow as tf

### layer
- 레이어 구축해서 모델 생성 

In [2]:
tf.keras.layers.Dense(32, activation='relu') #간단한 구조만 가능

In [3]:
tf.keras.layers.Dense(32)           
tf.keras.layers.BatchNormalization()
tf.keras.layers.Activation('relu')

In [ ]:
tf.keras.layers.Add  
tf.keras.layers.Average 
tf.keras.layers.DepthwiseConv2D #.keras.layers.Add  
tf.keras.layers.Average 
tf.keras.layers.DepthwiseConv2D #파라미터 줄이는 기법 
tf.keras.layers.Dropout #ensemble 효과 
tf.keras.layers.GRU
tf.keras.layers.Subtract
tf.keras.layers.UpSampling2D

In [ ]:
tf.keras.layers.ActivityRegularization  #값 크기 제한한

최신 모델은 단방향 아님

In [ ]:
tf.keras.models.Sequential #단방향  
tf.keras.models.Model      #multi-inputs,-outputs

- 모델구성(하이퍼 파라미터)이기 때문에 NAS, AutoML 사용해서 자동화 가능

## AutoML 
- TPOT, [AutoKeras](https://autokeras.com/)
  - 자동으로 머신러닝
  - 최신 기법 부족
### [TPOT](http://epistasislab.github.io/tpot/)
- 현재 프레임워크의 모든 머신러닝 알고리즘으로 가능한 모든 경우 탐색해서 파라미터 최적화도 자동으로 해줌 

In [6]:
!pip install tpot

In [8]:
from tpot import TPOTClassifier

In [9]:
from sklearn.datasets import load_iris

In [10]:
data=load_iris()

In [11]:
from tpot import TPOTClassifier

유전자 알고리즘: 세대를 거쳐가면서 적자생존

In [12]:
tp = TPOTClassifier(generations=10, population_size=10)

In [13]:
tp.fit(data.data, data.target)

TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=10,
               log_file=None, max_eval_time_mins=5, max_time_mins=None,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=10,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=0, warm_start=False)

In [14]:
tp.export('automl.py')

In [ ]:
# TPOT 결과 

import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectFwe, f_classif
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline

# NOTE: Make sure that the outcome column is labeled 'target' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
features = tpot_data.drop('target', axis=1)
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['target'], random_state=None)

# Average CV score on the training set was: 0.9866666666666667
exported_pipeline = make_pipeline(
    SelectFwe(score_func=f_classif, alpha=0.041),
    MLPClassifier(alpha=0.01, learning_rate_init=0.001)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

아직까지는 수동으로 구축하는게 더 성능 좋음

In [15]:
import tensorflow as tf

- 가능한 경우 중 잘 될만한 조합 찾아서 조합시켜 
> scikit-learn의 GridSearchCV: brute force 방식

In [16]:
from sklearn.model_selection import GridSearchCV       # brute force방식 , 
from sklearn.model_selection import RandomizedSearchCV # 확률기반

- compile에서  딕셔너리 이용 loss 여러 개 사용 가능

In [ ]:
model.fit #학습 누적되나 batch만큼 학습하기에는 부적합
model.train_on_batch  

- 하이퍼 파라미터 튜닝
- 학습과 동시에 튜닝하는 법 하이퍼 파라미터 튜닝
- 학습과 동시에 튜닝하는 법
Gradient Tape
Gradient Tape

### [KerasTuner](https://www.tensorflow.org/tutorials/keras/keras_tuner)
-  TensorFlow 에서 NN기반 최적의 모델 하이퍼파라미터 튜닝, 학습 알고리즘 하이퍼파라미터 튜닝## [KerasTuner](https://www.tensorflow.org/tutorials/keras/keras_tuner)
-  TensorFlow 에서 NN기반 최적의 모델 하이퍼파라미터 튜낭, 알고리즘 하이퍼파라미터 튜닝하는 라이브러리하는 라이브러리

In [18]:
!pip install -U keras-tuner

Requirement already up-to-date: keras-tuner in /usr/local/lib/python3.7/dist-packages (1.0.2)


In [19]:
import kerastuner as kt

In [20]:
dir(kt) #HyperParameter,RandomSearch, Oracle

['BayesianOptimization',
 'CloudLogger',
 'HyperModel',
 'HyperParameter',
 'HyperParameters',
 'Hyperband',
 'Logger',
 'Objective',
 'Oracle',
 'RandomSearch',
 'Tuner',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'applications',
 'check_tf_version',
 'config',
 'distribute',
 'division',
 'engine',
 'oracles',
 'print_function',
 'protos',
 'tuners',
 'utils']

In [23]:
(X_train,y_train),(X_test,y_test) =tf.keras.datasets.mnist.load_data()
X_train= X_train/255
X_test=X_test/255

In [24]:
#전처리 방법 2가지
#모델내에서 처리
tf.keras.layers.experimental.preprocessing.Resizing
tf.keras.layers.experimental.preprocessing.Rescaling
#데이터 세트 자체 처리
tf.keras.preprocessing.image_dataset_from_directory #다양한 전처리 기능 제공
tf.keras.preprocessing.image.ImageDataGenerator

tensorflow.python.keras.preprocessing.image.ImageDataGenerator

모델 만들기
1. 외부 연동 모델 

In [ ]:
tf.keras.wrappers.scikit_learn.KerasClassifier()   #함수방식으로 Scikit과 연동해서 다양한 머신러닝 테크닉 가져다 씀

In [45]:
def build_model(hp):
  model=tf.keras.models.Sequential()
  model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
  units=hp.Int('units' , min_value=32, max_value=512 ,step=16) #32~512를 16칸씩 증가해서 하이퍼 파라미터
  model.add(tf.keras.layers.Dense(units,activation='relu')) #units 128
  model.add(tf.keras.layers.Dense(10))
  learning=hp.Choice('learning_rate',values=[1e-2,1e-3,1e-4,1e-5])
  model.compile(optimizer=tf.keras.optimizers.Adam(learning),
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy']
                )
  return model

1. 처음부터 모델 만들어서 모델의 하이퍼파라미터 찾기
2. 이미 생성된 모델 모델의 하이퍼파라미터 찾기

In [46]:
#튜닝 방법, Scikit과연동됨연동됨
tuner = kt.Hyperband(build_model,'val_accuracy' ,2) #핵심 기능
kt.BayesianOptimization 
kt.RandomSearch 

INFO:tensorflow:Reloading Oracle from existing project ./untitled_project/oracle.json


kerastuner.tuners.randomsearch.RandomSearch

In [26]:
dir(kt) #

['BayesianOptimization',
 'CloudLogger',
 'HyperModel',
 'HyperParameter',
 'HyperParameters',
 'Hyperband',
 'Logger',
 'Objective',
 'Oracle',
 'RandomSearch',
 'Tuner',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'applications',
 'check_tf_version',
 'config',
 'distribute',
 'division',
 'engine',
 'oracles',
 'print_function',
 'protos',
 'tuners',
 'utils']

In [47]:
tuner.search(X_train,y_train, epochs=10,validation_split=0.3)

Trial 30 Complete [00h 01m 24s]
val_accuracy: 0.9703333377838135

Best val_accuracy So Far: 0.9782222509384155
Total elapsed time: 00h 18m 40s
INFO:tensorflow:Oracle triggered exit


In [49]:
best=tuner.get_best_hyperparameters()

In [50]:
dir(best[0])

['Boolean',
 'Choice',
 'Fixed',
 'Float',
 'Int',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_conditions',
 '_conditions_are_active',
 '_exists',
 '_get_name',
 '_hps',
 '_maybe_conditional_scope',
 '_name_scopes',
 '_register',
 '_retrieve',
 '_space',
 '_validate_name',
 'conditional_scope',
 'copy',
 'from_config',
 'from_proto',
 'get',
 'get_config',
 'is_active',
 'merge',
 'name_scope',
 'space',
 'to_proto',
 'values']

In [51]:
model = tuner.hypermodel.build(best[0]) #가장 좋은 모델 생성

In [52]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 384)               301440    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                3850      
Total params: 305,290
Trainable params: 305,290
Non-trainable params: 0
_________________________________________________________________


In [58]:
X_train=X_train.reshape(-1,28,28,1) #3차원 이미지로 만듦

In [57]:
dir(kt.HyperParameters) #4가지 경우Int, Float, Choice,  Boolean

['Boolean',
 'Choice',
 'Fixed',
 'Float',
 'Int',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_conditions_are_active',
 '_exists',
 '_get_name',
 '_maybe_conditional_scope',
 '_register',
 '_retrieve',
 '_validate_name',
 'conditional_scope',
 'copy',
 'from_config',
 'from_proto',
 'get',
 'get_config',
 'is_active',
 'merge',
 'name_scope',
 'space',
 'to_proto']

In [114]:
def build_model2(hp):
  inputs= tf.keras.Input(shape=(28,28,1)) 

  x=inputs

   #레이어, 필터 갯수 튜닝
  for i in range(hp.Int('n_layers',1,10)):
    x=tf.keras.layers.Conv2D( hp.Int('filters_'+ str(i),4,64,step=8),3, activation='relu' )(x)
    
  if hp.Choice('flatten',['flatten','avg']) =='avg':
    x=tf.keras.layers.GlobalAveragePooling2D()(x)
  else:
    x=tf.keras.layers.Flatten()(x)

  x=tf.keras.layers.Dense(units=hp.Int('units', 16, 64,step=8),activation='relu')(x)
  x=tf.keras.layers.Dropout(hp.Float('dropout_rate',min_value=.2, max_value=.4,step=.1))(x)
  outputs=tf.keras.layers.Dense(10,activation='softmax')(x)

  model=tf.keras.models.Model(inputs=inputs, outputs=outputs)
  model.compile(optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy']
                )
  return model

In [116]:
tuner2 = kt.RandomSearch(build_model2,'val_acc' ,2) 
tuner2.search_space_summary()

INFO:tensorflow:Reloading Oracle from existing project ./untitled_project/oracle.json
INFO:tensorflow:Reloading Tuner from ./untitled_project/tuner0.json
Search space summary
Default search space size: 2
units (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 16, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001, 1e-05], 'ordered': True}


In [117]:
tuner2.search(X_train,y_train,validation_split=0.2,epcohs=10)

INFO:tensorflow:Oracle triggered exit


In [119]:
best=tuner.get_best_hyperparameters()
model=tuner.hypermodel.build(best[0])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 384)               301440    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                3850      
Total params: 305,290
Trainable params: 305,290
Non-trainable params: 0
_________________________________________________________________


In [103]:
from kerastuner.tuners import Hyperband
from kerastuner.applications import HyperResNet

In [129]:
model= HyperResNet(input_shape=(28,28,1), classes=10 )

In [130]:
tuner3=Hyperband(model, 'val_accuracy', max_epochs=10)

INFO:tensorflow:Reloading Oracle from existing project ./untitled_project/oracle.json
INFO:tensorflow:Reloading Tuner from ./untitled_project/tuner0.json


Tensorflow2 에서 가장 어려운 것

In [ ]:
model.comiple(loss='',optimizer='')
model.fit

In [126]:
import tensorflow as tf

In [136]:
a=tf.Variable([2,3,4]) #변수
a

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [135]:
y=tf.multiply(a,a)
y #a의 제곱

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  9, 16], dtype=int32)>

### GradientTape
- 미분할 함수를 GradientTape 에 넣음
- Gradient 연산 값을 저장함 (테이프는 저장매체)

In [137]:
import inspect

In [140]:
print(inspect.getsource(tf.GradientTape().__enter__))

  def __enter__(self):
    """Enters a context inside which operations are recorded on this tape."""
    self._push_tape()
    return self



In [141]:
print(inspect.getsource(tf.GradientTape().__exit__))

  def __exit__(self, typ, value, traceback):
    """Exits the recording context, no further operations are traced."""
    if self._recording:
      self._pop_tape()



In [164]:
a=tf.Variable([2,3,4],dtype=tf.float32)
b=tf.constant([2,3,4],dtype=tf.float32)
y=tf.multiply(a,a)

In [167]:
with tf.GradientTape() as t:
  y=tf.multiply(a,a)

t.gradient(y,a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 6., 8.], dtype=float32)>

In [165]:
t.gradient(y,a) #y를 a에 관해서

In [169]:
with tf.GradientTape() as t:
  y=tf.multiply(b,b)

t.gradient(y,b) #상수를 미분하면 0(무의미)

##### watch
상수를 변수처럼 사용 할 수 있도록 만들어 줌 

In [170]:
with tf.GradientTape() as t:
  t.watch(b)            # 상수를 변수처럼 사용 할 수 있도록 만들어 줌 
  y=tf.multiply(b,b) 

t.gradient(y,b) 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 6., 8.], dtype=float32)>

---
예시 참고 : https://www.tensorflow.org/tutorials/quickstart/advanced
  - 모델의 예측과 실제 차이를 미분하는 공간 필요 

In [ ]:
@tf.function  
def train_step(images, labels):
  with tf.GradientTape() as tape:
    predictions = model(images)
    loss = loss_object(labels, predictions)  #loss함수를 미분 -> 최소화 
  gradients = tape.gradient(loss, model.trainable_variables) #trainable 학습을 통해서 loss를 최소화 하는 파라미터 
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

  train_loss(loss)
  train_accuracy(labels, predictions)

In [177]:
x=tf.ones((2,2))  #tf.Tensor -> 상수
y=tf.reduce_sum(x) #1+1+1+1=4

In [178]:
with tf.GradientTape() as t:
  t.watch(x)            
  z=tf.multiply(y,y)

t.gradient(z,x)  #값이 안나옴

In [184]:
with tf.GradientTape() as t:
  t.watch(x) 
  y=tf.reduce_sum(x)  #포함            
  z=tf.multiply(y,y)

t.gradient(z,y)   #값 나옴

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [185]:
with tf.GradientTape() as t:
  t.watch(x)
  y=tf.reduce_sum(x)     #포함       
  z=tf.multiply(y,y)

t.gradient(z,x)           #값 나옴

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [187]:
model=tf.keras.models.Sequential([
                                  #3x3 데이터가 각 4개의 units에 입력, 출력은 1개
                                 tf.keras.layers.Dense(4,input_shape=(3,3)),
                                 tf.keras.layers.Dense(1)
                                ])

In [188]:
model.summary() #학습 파라미터 21개 : 3x4 +4 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3, 4)              16        
_________________________________________________________________
dense_1 (Dense)              (None, 3, 1)              5         
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [191]:
3*4 +4 +4+1

21

In [193]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.20255578, -0.44520244,  0.85753584,  0.5719564 ],
        [ 0.90598285,  0.8105446 ,  0.2405119 ,  0.5164324 ],
        [ 0.12652493,  0.35953212,  0.7403592 ,  0.48062122]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.9037713 ],
        [-0.12859738],
        [ 0.12686706],
        [-0.6870853 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [194]:
model.trainable_variables  #모두 학습 가능해서 동일

[<tf.Variable 'dense/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.20255578, -0.44520244,  0.85753584,  0.5719564 ],
        [ 0.90598285,  0.8105446 ,  0.2405119 ,  0.5164324 ],
        [ 0.12652493,  0.35953212,  0.7403592 ,  0.48062122]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.9037713 ],
        [-0.12859738],
        [ 0.12686706],
        [-0.6870853 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [195]:
model.trainable=False
model.trainable_variables #없음

[]

In [196]:
model.trainable=True
model.trainable_variables #없음

[<tf.Variable 'dense/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.20255578, -0.44520244,  0.85753584,  0.5719564 ],
        [ 0.90598285,  0.8105446 ,  0.2405119 ,  0.5164324 ],
        [ 0.12652493,  0.35953212,  0.7403592 ,  0.48062122]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.9037713 ],
        [-0.12859738],
        [ 0.12686706],
        [-0.6870853 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [192]:
loss =tf.keras.losses.SparseCategoricalCrossentropy() #loss 함수 생성

In [ ]:
with tf.GradientTape() as t:
  model(X_train)
  l=loss(y_train, model(X_train))   #학습통한 예측과 정답간의 차이ith tf.GradientTape() as t:

t.gradient(l,model.trainable_variables) #batch 보다 작은 범위로 조정

In [ ]:
t.gradient(l,model.trainable_variables) #batch 보다 작은 범위로 조정